version: "3.0"

services:
    palntuml-server:
        container_name: palntuml-server
        image: plantuml/plantuml-server:jetty
        restart: always
        ports:
            - "8090:8080"
        networks:
            - custom

networks:
    custom:
        driver: bridge
